# Generated by Django 5.2.7 on 2025-10-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(max_length=2)),
                ('location', models.TextField(max_length=5)),
                ('description', models.TextField(max_length=10)),
            ],
        ),
    ]
