# Generated by Django 5.2.7 on 2025-10-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.TextField(max_length=50),
        ),
    ]
