# Generated by Django 5.2.7 on 2025-10-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50, unique=True)),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Action and Adventure', 'Action and Adventure'), ('Action and Comedy', 'Action and Comedy'), ('Action and Drama', 'Action and Drama'), ('Action and Fantasy', 'Action and Fantasy'), ('Action and Horror', 'Action and Horror'), ('Action and Mystery', 'Action and Mystery'), ('Action and Romance', 'Action and Romance'), ('Action and Sci-Fi', 'Action and Sci-Fi'), ('Action and Thriller', 'Action and Thriller'), ('Comedy', 'Comedy'), ('Romantic Comedy', 'Romantic Comedy'), ('Action Comedy', 'Action Comedy'), ('Drama and Comedy', 'Drama and Comedy'), ('Horror Comedy', 'Horror Comedy'), ('Adventure Comedy', 'Adventure Comedy'), ('Family Comedy', 'Family Comedy'), ('Drama', 'Drama'), ('Crime Drama', 'Crime Drama'), ('Historical Drama', 'Historical Drama'), ('Romantic Drama', 'Romantic Drama'), ('Mystery Drama', 'Mystery Drama'), ('Fantasy Drama', 'Fantasy Drama'), ('Drama and Thriller', 'Drama and Thriller'), ('Romance', 'Romance'), ('Romantic Thriller', 'Romantic Thriller'), ('Romantic Fantasy', 'Romantic Fantasy'), ('Romantic Adventure', 'Romantic Adventure'), ('Romantic Comedy', 'Romantic Comedy'), ('Romantic Drama', 'Romantic Drama'), ('Horror', 'Horror'), ('Psychological Horror', 'Psychological Horror'), ('Horror and Thriller', 'Horror and Thriller'), ('Horror and Mystery', 'Horror and Mystery'), ('Supernatural Horror', 'Supernatural Horror'), ('Thriller', 'Thriller'), ('Psychological Thriller', 'Psychological Thriller'), ('Mystery and Thriller', 'Mystery and Thriller'), ('Science Fiction', 'Science Fiction'), ('Fantasy', 'Fantasy'), ('Sci-Fi and Fantasy', 'Sci-Fi and Fantasy'), ('Action Sci-Fi', 'Action Sci-Fi'), ('Romantic Fantasy', 'Romantic Fantasy'), ('Fantasy Adventure', 'Fantasy Adventure'), ('Fantasy and Horror', 'Fantasy and Horror'), ('Family', 'Family'), ('Children', 'Children'), ('Animation', 'Animation'), ('Animated Comedy', 'Animated Comedy'), ('Animated Adventure', 'Animated Adventure'), ('Animated Fantasy', 'Animated Fantasy'), ('Crime', 'Crime'), ('Crime Thriller', 'Crime Thriller'), ('Crime Drama', 'Crime Drama'), ('War', 'War'), ('War Drama', 'War Drama'), ('Historical Fiction', 'Historical Fiction'), ('Documentary', 'Documentary'), ('Biography', 'Biography'), ('Music', 'Music'), ('Sports', 'Sports'), ('Musical Drama', 'Musical Drama'), ('Superhero', 'Superhero'), ('Western', 'Western'), ('Fantasy Adventure', 'Fantasy Adventure'), ('Other', 'Other')], max_length=100)),
                ('published_date', models.DateField()),
            ],
        ),
    ]
