# Generated by Django 5.2.7 on 2025-10-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculators',
            name='operation',
            field=models.CharField(choices=[('ADD', '+'), ('SUB', '-'), ('MUL', '×'), ('DIV', '÷')], default='ADD', help_text='Select the operation to perform', max_length=3),
        ),
    ]
