# Generated by Django 5.2.7 on 2025-10-30 12:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0002_calculators_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculators',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
