# Generated by Django 5.2.7 on 2025-10-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0003_alter_calculators_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculators',
            name='operation',
            field=models.CharField(choices=[('ADD', '+'), ('SUB', '-'), ('MUL', '×'), ('DIV', '÷'), ('FLOOR', '//'), ('MOD', '%')], default='ADD', help_text='Select the operation to perform', max_length=5),
        ),
    ]
